[2022-09-23T00:57:08.624+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: loading_data.load_tables manual__2022-09-23T00:57:04.784139+00:00 [queued]>
[2022-09-23T00:57:08.650+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: loading_data.load_tables manual__2022-09-23T00:57:04.784139+00:00 [queued]>
[2022-09-23T00:57:08.651+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-23T00:57:08.651+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-23T00:57:08.651+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-23T00:57:08.713+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): load_tables> on 2022-09-23 00:57:04.784139+00:00
[2022-09-23T00:57:08.721+0000] {standard_task_runner.py:54} INFO - Started process 1393 to run task
[2022-09-23T00:57:08.727+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'loading_data', 'load_tables', 'manual__2022-09-23T00:57:04.784139+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmpvbctugs1']
[2022-09-23T00:57:08.728+0000] {standard_task_runner.py:83} INFO - Job 120: Subtask load_tables
[2022-09-23T00:57:08.728+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/load_data.py
[2022-09-23T00:57:10.687+0000] {task_command.py:384} INFO - Running <TaskInstance: loading_data.load_tables manual__2022-09-23T00:57:04.784139+00:00 [running]> on host 211e88f8c2ad
[2022-09-23T00:57:10.907+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=loading_data
AIRFLOW_CTX_TASK_ID=load_tables
AIRFLOW_CTX_EXECUTION_DATE=2022-09-23T00:57:04.784139+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-23T00:57:04.784139+00:00
[2022-09-23T00:57:17.771+0000] {logging_mixin.py:117} INFO - Failed  ---- (psycopg2.errors.DependentObjectsStillExist) cannot drop table cars because other objects depend on it
DETAIL:  constraint fk_cars on table trajectories depends on table cars
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE cars]
(Background on this error at: https://sqlalche.me/e/14/2j85)
[2022-09-23T00:57:17.815+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-09-23T00:57:17.909+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=loading_data, task_id=load_tables, execution_date=20220923T005704, start_date=20220923T005708, end_date=20220923T005717
[2022-09-23T00:57:18.015+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-09-23T00:57:18.109+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
