[2022-09-22T23:17:44.255+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: loading_data.insert_data manual__2022-09-22T23:17:34.663836+00:00 [queued]>
[2022-09-22T23:17:44.321+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: loading_data.insert_data manual__2022-09-22T23:17:34.663836+00:00 [queued]>
[2022-09-22T23:17:44.321+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-22T23:17:44.321+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-22T23:17:44.322+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-22T23:17:44.462+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): insert_data> on 2022-09-22 23:17:34.663836+00:00
[2022-09-22T23:17:44.480+0000] {standard_task_runner.py:54} INFO - Started process 21514 to run task
[2022-09-22T23:17:44.483+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'loading_data', 'insert_data', 'manual__2022-09-22T23:17:34.663836+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmpb18qqsrx']
[2022-09-22T23:17:44.492+0000] {standard_task_runner.py:83} INFO - Job 64: Subtask insert_data
[2022-09-22T23:17:44.493+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/load_data.py
[2022-09-22T23:17:46.814+0000] {task_command.py:384} INFO - Running <TaskInstance: loading_data.insert_data manual__2022-09-22T23:17:34.663836+00:00 [running]> on host c1ab2cb1bbac
[2022-09-22T23:17:47.907+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=loading_data
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-22T23:17:34.663836+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-22T23:17:34.663836+00:00
[2022-09-22T23:17:47.928+0000] {logging_mixin.py:117} INFO - Failed  ---- [Errno 2] No such file or directory: '../data/cars_table.csv'
[2022-09-22T23:17:47.929+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-09-22T23:17:47.952+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=loading_data, task_id=insert_data, execution_date=20220922T231734, start_date=20220922T231744, end_date=20220922T231747
[2022-09-22T23:17:48.199+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-09-22T23:17:48.283+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
